config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations"}

  resources :users do
    resources :images
    resources :reviews
    resources :contact
  end

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
  get '/test_mode', to: 'users#test', as: 'test_mode'
  get '/search', to: 'users#search', as: 'users_search'
  get '/welcome', to: 'users#welcome', as: 'welcome_form'
  post '/welcome', to: 'users#postcode_added', as: 'welcome_post'
  

  # get '/users/:id/search', to: 'users#search', as: 'users_search'
  # get '/search', to: 

end

app/models/user.rb
class User < ApplicationRecord
  
  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#", :square => "100x100#"  }, default_url: "no-image.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  acts_as_mappable :default_units => :miles,
  :default_formula => :sphere,
  :distance_field_name => :distance,
  :lat_column_name => :location_lat,
  :lng_column_name => :location_lon
  
  validates :name, presence: true
  validates :email, presence: true

  enum status: [:rating]
  has_many :reviews, -> { order(created_at: :desc) }
  has_many :ratings
  has_many :images

  after_initialize :init

  def init
    self.location_lat  ||= -0.09039        
    self.location_lon ||= 51.51264     
    self.range_to ||= 40 
    self.rating ||= 1
    self.average_rating ||= av_rating
  end
  #carrierwave upload mounting
  #mount_uploader :avatar, AvatarUploader
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def av_rating
    if reviews.count > 0 && ((reviews.map(&:rating).compact.sum.to_f)/(reviews.map(&:rating).compact.count)).round >= 1
        return ((reviews.map(&:rating).compact.sum.to_f)/(reviews.map(&:rating).compact.count)).round
    else 1
    end
  end

  def self.search(term)
    if term
      where('name ILIKE ?', "%#{term}%")
    else
      all
    end
  end

  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  #POST /resource/sign_in
  #def create
  
      
      #redirect_to '/index'
   
  
  #end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute, :user, :email, :params, :avatar])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :authenticate_user!, except: [:index, :show] 

  def index
    @current_user=current_user
      @users= User.all
  end

  def search
    @current_user=current_user
    begin
      if params.has_key?(:name)
        @users = User.search(session[:postcode]).order("created_at DESC")
      elsif params.has_key?(:location) && valid_postcode(session[:postcode])
        @users = User.by_distance(:origin => session[:postcode]).within(current_user.range_to , :origin => session[:postcode])
      elsif params.has_key?(:all)
        @users = User.all
      elsif params.has_key?(:rating)
        @users = User.all.sort_by(&:av_rating).reverse
      else
        flash[:alert] = "** Postcode not valid **"
        @users=User.all
      end
    rescue
      @users = User.all.order("created_at DESC")
      flash[:alert] = "** Bad Search Parameters **"
    end
    ensure
      render 'index'
  end

  def postcode_added
    @current_user = current_user
    session[:postcode]=params[:user][:postcode]
    if valid_postcode(session[:postcode])
      begin
      @users = User.by_distance(:origin => session[:postcode]).within(current_user.range_to , :origin => session[:postcode])
      rescue
      @users = User.all
      flash[:alert] = "** Bad Search Parameters **"
      end
    else
      @users = User.search(session[:postcode]).order("created_at DESC")
    end
  ensure
    render 'index'
  end

  def show
    @image=Image
    @user = User.find(params[:id]) || guest_user
    @current_user = current_user
    @reviews = Review.where("user_id = #{@user.id}").order("created_at ASC")
    @review = Review.new
  end

  def edit
    @current_user = current_user
    @user = User.find(params[:id])
  end

  def update
    #binding.pry
    @current_user = current_user
    @user = User.find(params[:id])
    if @user == current_user || session[:test_mode]==true
      @user.update_attributes(user_params)
      params[:file]?@user.avatar = params[:file]:nil
      if params[:search].length>4
        pc = Geokit::Geocoders::MultiGeocoder.geocode (params[:search])
        @user.update_attributes(location_lat:pc.lat,location_lon:pc.lng)
      end
      @user.save!
      flash[:notice]="**User updated**"
      redirect_to :action => "show", :id => params[:id].to_i
    else 
      redirect_to ('/')
    end
  end

  def valid_postcode (postcode)
    postcode.match(/\b((?:(?:gir)|(?:[a-pr-uwyz])(?:(?:[0-9](?:[a-hjkpstuw]|[0-9])?)|(?:[a-hk-y][0-9](?:[0-9]|[abehmnprv-y])?)))) ?([0-9][abd-hjlnp-uw-z]{2})\b/)? true : false
  end
    

  private
    def user_params
      params.require(:user).permit(:email, :bio, :avatar, :user_id, :id, :range_to, :location_lat, :location_lon, :search, :is_a_chef, :is_chef?, :max_party_size, :price_per_head, :postcode, :format)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_welcome.html.erb
<div class="welcome">
  <!-- <h2>Please enter your Postcode:</h2> -->
      <%= form_for @current_user, url: welcome_post_path, method: 'post'  do |f| %>

    <div id="sb-search" class="sb-search">
      <% if session[:postcode]!=nil%>
      <% place_val = 'searching by: ' + session[:postcode] %>
      <% else %>
       <% place_val = "Enter a postcode or a name" %>
       <% end %>
      <%= f.text_field :postcode, autofocus: true, autocomplete: "SL44NP", placeholder: place_val, :class => "sb-search-input"%>
        <%= f.hidden_field :id %>
    </div>

    <div>
      <%= f.submit "GO", :class => "sb-search-submit"%>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="userpage">
    <h2>Edit Profile</h2><br>
    <h3><%= @user.name %><br>   </h3>
    <br>
    <div id="getLocation"><%=fa_icon "location-arrow",class: "fa-2x fal",id:'location_icon'%></div>
    <div id='mapid' style="width:100%;top:10%;left:0%"></div></br>
    <%= form_for @user, url: user_path(@user), method: 'put'  do |f| %>
        <div class="field">
            <%= text_field_tag :search, params[:search], placeholder: "Get location from Postcode (SL41PN)" %>
        </div>
        <div class="field" id="range_to">
            <%= f.label "Distance i will travel for a job (Miles)" %>
        <br/>
            <%= f.text_field :range_to, autofocus: true, autocomplete: "range_to"%>
        </div>
        <div class="field">
            <%= f.label :email %>
        <br/>
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>
        <div class="field">
            <%= f.label "Cover Photo" %><br>
            <%= f.file_field :avatar %>
        </div>
        <br>
        <div class="avatar">
            <% if @user.avatar.file? %>
                <%= image_tag @user.avatar.url, id: "edit_image"%>
            <% end %>
        </div>
        <div class="field">
            <%= f.label :biography%>
            <br/>
            <%= f.text_area :bio, autofocus: true, autocomplete: "bio" %>
         </div>
        <div class="field">
            <%= f.label "Maximum Party Size" %><br />
            <%= f.text_field :max_party_size, autofocus: true, autocomplete: "5" %>
        </div>
        <div class="field">
            <%= f.label "Average price per head (£)"%><br />
            <%= f.text_field :price_per_head, autofocus: true, autocomplete: "50" %>
        </div>
            <%= f.hidden_field :location_lat, autofocus: true, autocomplete: "location_lat" %>
            <%= f.hidden_field :location_lon, autofocus: true, autocomplete: "location_lon" %>
            <%= f.hidden_field :id, :value => params[:id] %>
        <div class="actions">
            <%= f.submit "Update" %>
        </div>
    <% end %>
    </br>
        <%= link_to "Back", :back, id: 'small_back' %>
 <script type="text/javascript">

 var circle, originalCircle, edited, marker_edited, marker, loc_lat_lng

    $('#user_range_to').keyup(function(){
        !edited?mymap.removeLayer(originalCircle):null
        circle?mymap.removeLayer(circle):null
        edited = true
        if (!marker_edited){
            circle=L.circle([<%="#{@user.location_lat},#{@user.location_lon}],"%>$("#user_range_to").val()*1000,{color: '#FF0000'}).addTo(mymap)
        } else {
        circle=L.circle(loc_lat_lng,$("#user_range_to").val()*1000,{color: '#FF0000'}).addTo(mymap)
        }
    })

    var mymap = L.map('mapid').setView([<%="#{@user.location_lat},#{@user.location_lon}"%>],7);

    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        maxZoom: 18,
        id: 'mapbox.streets',
        accessToken: 'pk.eyJ1IjoidGhvbWFzY2FsbHVtYnJvb2siLCJhIjoiY2pnNm9hOTUxMjlyNjJ3b2gybXl2OGpvNSJ9.6FSzBSK3H6063Afj38PSIQ'
        }).addTo(mymap);
    
    originalCircle=L.circle([<%="#{@user.location_lat},#{@user.location_lon}],"%>$("#user_range_to").val()*1000,{color: '#FF0000'}).addTo(mymap)
    
    var goChefIcon = L.icon({
        iconUrl: '/gochef_logo.png',
        iconSize:     [38, 95], 
        iconAnchor:   [22, 94],  
        popupAnchor:  [-3, -76], 
        className: 'mapIcon'
    });

    function renderMarkers (e){
        mymap.removeLayer(marker)
        loc_lat_lng=e
        marker=L.marker([e.lat,e.lng], {icon: goChefIcon}).addTo(mymap);
        circle?mymap.removeLayer(circle):null
        !edited?mymap.removeLayer(originalCircle):edited=true
        circle=L.circle([e.lat,e.lng],$("#user_range_to").val()*1000,{color: '#FF0000'}).addTo(mymap)
        marker_edited=true
    }
    function onMapClick(e) {
        $('#user_location_lat').val(e.latlng.lat)
        $('#user_location_lon').val(e.latlng.lng)
        mymap.panTo(e.latlng)
        renderMarkers(e.latlng) 
    }
    mymap.on('click', onMapClick);

    !marker_edited?marker=L.marker([<%="#{@user.location_lat},#{@user.location_lon}"%>], {icon: goChefIcon}).addTo(mymap):null

    $("#getLocation").click(()=>{
        mymap.locate({setView: true, watch: true}).setView(7)
    })

</script>

app/views/users/index.html.erb
<div class="cover">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
  <%= render(:partial => 'users/welcome') %>
</div>

<div class = "container">
  <div class ="right">
<div class="list">
    <% @users.each do |user| %>
      <% if user.is_a_chef %>
          <div class="chef-list" id="chef-<%= user.id %>"">
            <div class="chef-list-profile">
              <div class="small-avatar" style="background-image: url(<%= user.avatar.url(:thumb)%>)"></div>

            </div>
            <div class="list-content">
              <%= link_to "#{user.name}", user_path(user) %>
                
                  <div class="ratings_bar">
                    <% 5.times do |i|%>
                     <% if user.av_rating != nil && i && user.av_rating > i %>
                       <%= link_to(raw(fa_icon "spoon", class: "fa-1x", class: "spoon"), user_path(user, :id => user.id))%> 
                     <% else %>
                       <%= link_to(raw(fa_icon "spoon", class: "fa-1x", class: "spoon_empty"), user_path(user, :id => user.id))%> 
                       <!--<%= link_to(raw("<i class='fa fa-star'></i>"), user_path(user, :id => user.id)) %> -->
                     <% end %>
                    <% end %>
                  </div>
                  <br><br>
                  <button class="button show">
                      <%= link_to "Show", user_path(user)%>
                  </button>
                </div>
            </div>             
        <% end %>
    <% end %>
</div>
</div>

<div class ="search">
        <div id="search_box">
        <div id="location" class="box_text">LOCATION</div>
         <div id="cross_line"></div>
        <div id="rating" class="box_text">RATING</div>
        <div id="line"></div>
        <div id="name" class="box_text">NAME</div>
        </div>
      </div>

    </div>
<script>

$("#location").click(()=>{window.location.replace('/search?location=true')})
$("#name").click(()=>{window.location.replace('/search?name=true')})
$("#rating").click(()=>{window.location.replace('/search?rating=true')})
</script>

app/views/users/show.html.erb
<div class="userpage">


  <!-- chef title -->
  <div class ="profile_title"> 
   <div class ="sub_header">
      Maximum party size: <%= @user.max_party_size %><br>
      Price per head: <%= @user.price_per_head %>
    </div>
  <div id ="chef_gallery">
      <% @user.images.each do |i| %>
        <div class="photos" style="background-image: url(<%= i.image.url %>" id="<%=i.image.url%>"></div>
      <% end %>
  </div>
  <div class ="profile">     
    <% if @user.avatar.file? %>
      <%= image_tag @user.avatar.url(:medium)%>
    <% end %>
  </div>
  <div id="mapid"></div>
  <link href="https://fonts.googleapis.com/css?family=Play" rel="stylesheet">
  <script type="text/javascript">
    var mymap = L.map('mapid').setView([<%="#{@user.location_lat},#{@user.location_lon}"%>],6);
    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        maxZoom: 18,
        zoomControl: false,
        id: 'mapbox.streets',
        accessToken: 'pk.eyJ1IjoidGhvbWFzY2FsbHVtYnJvb2siLCJhIjoiY2pnNm9hOTUxMjlyNjJ3b2gybXl2OGpvNSJ9.6FSzBSK3H6063Afj38PSIQ'
      }).addTo(mymap);
    L.circle([<%="#{@user.location_lat},#{@user.location_lon}],#{(@user.range_to||50)*1000}"%>,{color: '#FF0000'}).bindTooltip('Area served by <%=@user.name%>').addTo(mymap)
    var goChefIcon = L.icon({
      iconUrl: '/gochef_logo.png',
      iconSize:     [38, 95], 
      iconAnchor:   [22, 94], 
      popupAnchor:  [-3, -76], 
      className: 'mapIcon'
    });
    L.marker([<%="#{@user.location_lat},#{@user.location_lon}"%>], {icon: goChefIcon}).addTo(mymap);
    $(".photos").click(function() {
      console.log(this.id)
    window.open(this.id, '_blank', 'location=yes,height=570,width=520,scrollbars=yes,status=yes')
    });
       
</script>
    <p class ="title"><%= @user.name %></p>
    <br>
    <% if @user == current_user %>
        <button class="button edit">
         <%= link_to("My Gallery", new_user_image_path(@user) ) %> 
        </button>
    <% elsif session[:user_type] == "registered" %>
        <button class="button edit">
        <%= link_to("Contact", new_user_contact_path(@user) ) %> 
        </button>
      <% end %>
    <button class = "button back">
      <%= link_to("Back to the chefs", "/" ) %>
    </button>
    <div class="bio">
      <% if @user.bio %>
        <%= @user.bio.gsub(/\n/, '<br>') %>
        <% else %>
        ** This chef hasn't submitted a bio **
      <% end %>
      <section class="reviews">
        <div class="review">
          <% if @current_user.name != "guest" && @user != @current_user %>
            <%= render(:partial => 'reviews/review')%></br>
          <% else %>
            <br>
          <% end %>
          <%= render(:partial => 'reviews/show') %>
        </div>
      </section>
    </div>
  </div>

app/views/users/test.html.erb
<div class="page">
<h2>Test Mode is <% if @testmode==true %>
                    <%= "On" %>
                    <% else %>
                    <%= "Off" %>
                    <% end %>
                     <button class = "button back">
      <%= link_to("Back to the chefs", "/" ) %>
    </button>
    </div>

app/views/users/update.html.erb
<div class="page">
  <button class = "button back">
    <%= link_to("home", "/" ) %>
  </button>
  <br>
  </div>