config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations"}

  resources :users do
    resources :images
    resources :reviews
    resources :contact
  end

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
  get '/test_mode', to: 'users#test', as: 'test_mode'
  get '/search', to: 'users#search', as: 'users_search'
  get '/welcome', to: 'users#welcome', as: 'welcome_form'
  post '/welcome', to: 'users#postcode_added', as: 'welcome_post'
  

  # get '/users/:id/search', to: 'users#search', as: 'users_search'
  # get '/search', to: 

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  #before_action :authenticate_user!, except: [:index]


  def index
    @reviews = Review.all
  end

  def show
    @user = User.find(params[:id])
    @user_type = guest_user ? :guest : :registered
    @reviews = Review.where("user_id = #{@user.id}")
    @review = Review.new(:user_id => @user.id)
  end

  def new
    @review = Review.new
    @user=User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @review = @user.reviews.create!(review_params)
    @review.reviewer_name = current_user.name
    if @review.save
      redirect_to(user_path(@user))
    else
      flash[:error]="**Error saving review**"
      render('users#show')
    end
  end

  private

    def review_params
      params.require(:review).permit(:comment, :rating, :avatar, :user_id)
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review.html.erb
      <div class="post_review">
        <%= form_for @review, url: user_reviews_path(@user) do |f| %>
          <div class="field">
            <%= f.label "Leave a review." %>
            <br />
            <%= f.text_area :comment, autofocus: false, autocomplete: "review" %>
          </div>
          <%= f.label "Add a photo" %><br>
          <%= f.file_field :avatar%>


          <table class ="rating_input">
              <tr>
                <td><%= f.radio_button :rating, 1 %> <%= f.label "1" %></td>
                <td><%= f.radio_button :rating, 2 %> <%= f.label "2" %></td>
                <td><%= f.radio_button :rating, 3 %> <%= f.label "3" %></td>
                <td><%= f.radio_button :rating, 4 %> <%= f.label "4" %></td>
                <td><%= f.radio_button :rating, 5 %> <%= f.label "5" %></td>
              </tr>
          </table> 
       
          <div class="actions">
            <%= f.submit "Post" %>
          </div>
        <% end %>
      </div>
      <br>
      <hr>
      <br>
    
    

app/views/reviews/_show.html.erb
        <% @user.reviews.each do |review| %>
        <div class="c">    
         <% if review.avatar.file? %>
            <div class="review_pic"> <%=image_tag review.avatar.url(:thumb)%> </div>
            <script><%= review.avatar.url%></script>
        <% end %>
           <div class="rating">
                <% 5.times do |i|%>
                   <% if review.rating && i && review.rating > i %>
                     <%= link_to(raw(fa_icon "spoon", class: "fa-1x", class: "spoon"), user_path(@user))%> 
                       <% else %>
                        <%= link_to(raw(fa_icon "spoon", class: "fa-1x", class: "spoon_empty"), user_path(@user))%> 
                              <% end %>
                            <% end %>
                            <p><%= simple_format(review.comment) %> <p>
                            <div class="created_at"> <%=  "#{review.created_at.to_s.chomp('UTC')} by #{review.reviewer_name}" %></div>
                            </div>
                        </div>
            <br>
            
            <!--switched off temporarily, cant seem to get font smaller that 12?
            <div class="created_at"> <%= review.created_at %></div>
            </div>
            -->
           <% end %>
      

app/views/reviews/delete.html.erb
<h1>Reviews#delete</h1>
<p>Find me in app/views/reviews/delete.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>