config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations"}

  resources :users do
    resources :images
    resources :reviews
    resources :contact
  end

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
  get '/test_mode', to: 'users#test', as: 'test_mode'
  get '/search', to: 'users#search', as: 'users_search'
  get '/welcome', to: 'users#welcome', as: 'welcome_form'
  post '/welcome', to: 'users#postcode_added', as: 'welcome_post'
  

  # get '/users/:id/search', to: 'users#search', as: 'users_search'
  # get '/search', to: 

end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader

  #this allows uploading of multiple images
  # If you use SQLite, add this line.ß
  belongs_to :user, optional: true
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def new
    @user = User.find(params[:user_id])
    @image = Image.new
  end

  def destroy
    p User.find(params[:user_id])
    User.find(params[:user_id]).images.delete(params[:id])
    flash[:notice]="**Image Deleted**"
    redirect_to new_user_image_path(current_user)
  end
  def create
    @user = User.find(params[:user_id])
    if @user == current_user && params[:image]
      @image = @user.images.new(image_params)
      if @image.save
        redirect_to new_user_image_path(params[:user_id])
        flash[:notice]="**Image Saved**"
      else
        flash[:notice]="**Image Not Saved**"
        render :new
      end
    else
      redirect_to user_path(params[:user_id])
    end
  end

  private

  def image_params
    params.require(:image).permit(:image,:id)
  end
end


#logic for allowing multiple files to be uploaded at once, i will implement this as a feature at a later date
#params.require(:image).permit({images: []})

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/new.html.erb
  <div class="user page">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <div class="gallery_form">
        <h2>Upload images to your gallery</h2>
        <h3><%= current_user.name %></h3>
      </div>
    <%= form_for @image, :html=> {:id => 'gallery_form'} , url: user_images_path(current_user), method: 'post'  do |f| %>
      <div class="gallery_text">
        <div id="photo_frame" class="photo_frame"></div>
          <%= f.label "Add a photo" %><br>
          <%= f.file_field :image %>
        </div>
        <div class="actions">
        <%= f.submit "Update" %>
        </div>
    <% end %>
    <div id="gallery">
      <% @user.images.each_with_index do |i,l| %>
        <div class="pic_frame" style="background-image: url(<%= i.image.url %>">
         <div class="picture_button" ><%=fa_icon "trash",class: "fa-1x",id: i.id %></div>
        </div>
      <% end %>         
    </div>
  <% if @image.errors.any? %>
    <h4><%= pluralize(@image.errors.count, "error") %> prohibited this file from being saved</h4>
      <ul class="error_list">
        <% @image.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>
    </br>
    <%= link_to "Back", user_path(current_user), id: "small_back" %>
  </div>
<script>
$('.fa-1x').click(function(){
  if (confirm('are you sure you want to delete this image?')){
    $.ajax({
        url: '/users/<%=current_user.id%>/images/'+this.id,
        type: 'DELETE',
        success: function(result) {
        }
    })
  }
})
</script>
</div>