config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations"}

  resources :users do
    resources :images
    resources :reviews
    resources :contact
  end

 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
  get '/test_mode', to: 'users#test', as: 'test_mode'
  get '/search', to: 'users#search', as: 'users_search'
  get '/welcome', to: 'users#welcome', as: 'welcome_form'
  post '/welcome', to: 'users#postcode_added', as: 'welcome_post'
  

  # get '/users/:id/search', to: 'users#search', as: 'users_search'
  # get '/search', to: 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <title>Go Chef</title>
      <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500|Roboto:400,500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Baloo+Bhai|Original+Surfer" rel="stylesheet">
    <div class="nav-bar">
      <div class="logo">
        <%= link_to (image_tag ("gochef_logo.png"), class: 'logo'), "/" %>
      </div>  
      <!--
      <div class ="search search_container">
        <%= form_tag(users_path, method: :get) do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Chefs" %>
          <%= submit_tag 'Search', name: nil, :class => "search_button" %>
        <% end %>
      </div>-->
      <div class="nav-links">
           <% if current_user == @user %>
                <button class="button blue_button">
                    <%=link_to(raw("<i class='fa fa-cog'></i>"), edit_user_path(current_user.id))%> 
                 </button>
          <% end %>
      <!--
        <button class = "button sign_up">
          <% if session[:test_mode] %>
            <%= link_to "test mode", test_mode_path,{:style=>'color:#00FF00;'}%>
          <% else %>
           <%= link_to "test mode", test_mode_path,{:style=>'color:#000000;'}%>
          <% end %>
      </button>-->
      <script>
      console.log('<%=session[:user_type]%>')
      </script>
        <% if current_user.name != "guest" %>
          <button class = "button sign_up">
            <%= link_to "sign out", destroy_user_session_path, method: :delete %>
          </button>
        <% else %>
          <button class = "button sign_in">
            <%= link_to "sign in", new_user_session_path %>
          </button>
          <button class = "button sign_up">
            <%= link_to "Join", new_user_registration_path %>
          </button>
        <% end %>
      </div>
    </div>
  </head>
  <body >


    <%= yield %>
  </body>
</html>